version: 2
executorType: docker
containerInfo:
  - image: node:5.10.0
stages:
  build:
    workDir: /home/ubuntu/demo-react-working
    steps:
      - type: checkout
      - type: shell
        name: Pre-Dep
        command: mkdir /home/ubuntu/artifacts
      - type: shell
        name: Install Dependencies
        command: npm install
      - type: shell
        name: Install 3rd Party Libs for Cypress
        command: apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1
      - type: shell
        name: Install Cypress CLI Tools
        command: npm install -g cypress-cli
      - type: shell
        name: Start server
        command: npm start -- --silent &
      - type: shell
        name: Cypress Test
        command: cypress ci
      - type: artifacts-store
        path: /home/ubuntu/artifacts
